CREATE TABLE DEPARTMENT (
    DEPT_ID NUMBER(5) PRIMARY KEY,
    DEPT_NAME VARCHAR2(50) NOT NULL,
    LOCATION VARCHAR2(30)
);

CREATE TABLE DOCTOR (
    DOCTOR_ID NUMBER(5) PRIMARY KEY,
    DOCTOR_NAME VARCHAR2(50) NOT NULL,
    DEPT_ID NUMBER(5) NOT NULL,
    SPECIALIZATION VARCHAR2(50),
    FEES NUMBER(8,2) CHECK (FEES > 0),

    CONSTRAINT FK_DOCTOR_DEPT
        FOREIGN KEY (DEPT_ID)
        REFERENCES DEPARTMENT(DEPT_ID)
);

CREATE TABLE PATIENT (
    PATIENT_ID NUMBER(5) PRIMARY KEY,
    PATIENT_NAME VARCHAR2(50) NOT NULL,
    GENDER CHAR(1),
    CITY VARCHAR2(30) NOT NULL,
    PHONE VARCHAR2(15) UNIQUE,
    EMAIL VARCHAR2(50) UNIQUE
);

CREATE TABLE APPOINTMENT (
    APPOINTMENT_ID NUMBER(6) PRIMARY KEY,
    PATIENT_ID NUMBER(5) NOT NULL,
    DOCTOR_ID NUMBER(5) NOT NULL,
    APPOINTMENT_DATE DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(20) DEFAULT 'SCHEDULED',

    CONSTRAINT FK_APPT_PATIENT
        FOREIGN KEY (PATIENT_ID)
        REFERENCES PATIENT(PATIENT_ID),

    CONSTRAINT FK_APPT_DOCTOR
        FOREIGN KEY (DOCTOR_ID)
        REFERENCES DOCTOR(DOCTOR_ID),

    CONSTRAINT CHK_APPT_STATUS
        CHECK (STATUS IN ('SCHEDULED', 'COMPLETED', 'CANCELLED'))
);

CREATE TABLE BILLING (
    BILL_ID NUMBER(6) PRIMARY KEY,
    APPOINTMENT_ID NUMBER(6) NOT NULL,
    AMOUNT NUMBER(10,2) CHECK (AMOUNT > 0),
    PAYMENT_STATUS VARCHAR2(20) DEFAULT 'PENDING',
    BILL_DATE DATE DEFAULT SYSDATE,

    CONSTRAINT FK_BILL_APPT
        FOREIGN KEY (APPOINTMENT_ID)
        REFERENCES APPOINTMENT(APPOINTMENT_ID),

    CONSTRAINT CHK_PAYMENT_STATUS
        CHECK (PAYMENT_STATUS IN ('PAID', 'PENDING'))
);

ALTER TABLE PATIENT ADD ADDRESS VARCHAR2(100);

DESC PATIENT;

INSERT INTO DEPARTMENT VALUES (10, 'Cardiology', 'Block A');
INSERT INTO DEPARTMENT VALUES (20, 'Orthopedics', 'Block B');
INSERT INTO DEPARTMENT VALUES (30, 'Pediatrics', 'Block C');
INSERT INTO DEPARTMENT VALUES (40, 'General Medicine', 'Block A');

INSERT INTO DOCTOR VALUES (201, 'Dr. Suresh Kumar', 10, 'Cardiologist', 1200);
INSERT INTO DOCTOR VALUES (202, 'Dr. Meena Devi', 10, 'Cardiologist', 1000);
INSERT INTO DOCTOR VALUES (203, 'Dr. Ravi Shankar', 20, 'Orthopedic Surgeon', 1500);
INSERT INTO DOCTOR VALUES (204, 'Dr. Pooja Singh', 20, 'Orthopedic Surgeon', 900);
INSERT INTO DOCTOR VALUES (205, 'Dr. Ganesh Rao', 30, 'Pediatrician', 700);
INSERT INTO DOCTOR VALUES (206, 'Dr. Kavya Reddy', 30, 'Pediatrician', 800);
INSERT INTO DOCTOR VALUES (207, 'Dr. Manoj Kumar', 40, 'General Physician', 500);
INSERT INTO DOCTOR VALUES (208, 'Dr. Deepa Nair', 40, 'General Physician', 600);

INSERT INTO PATIENT VALUES (301, 'Arun Kumar', 'M', 'Chennai', '9876543210', 'arun@gmail.com', 'Anna Nagar');
INSERT INTO PATIENT VALUES (302, 'Priya Sharma', 'F', 'Bangalore', '9876543211', 'priya@gmail.com', 'Indiranagar');
INSERT INTO PATIENT VALUES (303, 'Rahul Singh', 'M', 'Mumbai', '9876543212', 'rahul@gmail.com', 'Andheri');
INSERT INTO PATIENT VALUES (304, 'Sneha Reddy', 'F', 'Hyderabad', '9876543213', 'sneha@gmail.com', 'Banjara Hills');
INSERT INTO PATIENT VALUES (305, 'Karthik Raj', 'M', 'Chennai', '9876543214', 'karthik@gmail.com', 'Velachery');
INSERT INTO PATIENT VALUES (306, 'Divya Nair', 'F', 'Kochi', '9876543215', 'divya@gmail.com', 'Edappally');
INSERT INTO PATIENT VALUES (307, 'Vijay Kumar', 'M', 'Hyderabad', '9876543216', 'vijay@gmail.com', 'Kukatpally');
INSERT INTO PATIENT VALUES (308, 'Anitha Mary', 'F', 'Puducherry', '9876543217', 'anitha@gmail.com', 'White Town');

INSERT INTO APPOINTMENT VALUES (4001, 301, 201, TO_DATE('01-06-2025','DD-MM-YYYY'), 'COMPLETED');
INSERT INTO APPOINTMENT VALUES (4002, 302, 203, TO_DATE('02-06-2025','DD-MM-YYYY'), 'COMPLETED');
INSERT INTO APPOINTMENT VALUES (4003, 303, 205, TO_DATE('03-06-2025','DD-MM-YYYY'), 'COMPLETED');
INSERT INTO APPOINTMENT VALUES (4004, 304, 207, TO_DATE('04-06-2025','DD-MM-YYYY'), 'CANCELLED');
INSERT INTO APPOINTMENT VALUES (4005, 305, 201, TO_DATE('05-06-2025','DD-MM-YYYY'), 'COMPLETED');
INSERT INTO APPOINTMENT VALUES (4006, 306, 204, TO_DATE('06-06-2025','DD-MM-YYYY'), 'SCHEDULED');
INSERT INTO APPOINTMENT VALUES (4007, 307, 206, TO_DATE('07-06-2025','DD-MM-YYYY'), 'COMPLETED');
INSERT INTO APPOINTMENT VALUES (4008, 308, 208, TO_DATE('08-06-2025','DD-MM-YYYY'), 'COMPLETED');
INSERT INTO APPOINTMENT VALUES (4009, 301, 207, TO_DATE('15-06-2025','DD-MM-YYYY'), 'COMPLETED');
INSERT INTO APPOINTMENT VALUES (4010, 303, 201, TO_DATE('16-06-2025','DD-MM-YYYY'), 'CANCELLED');

INSERT INTO BILLING VALUES (7001, 4001, 1200, 'PAID', TO_DATE('01-06-2025','DD-MM-YYYY'));
INSERT INTO BILLING VALUES (7002, 4002, 1500, 'PAID', TO_DATE('02-06-2025','DD-MM-YYYY'));
INSERT INTO BILLING VALUES (7003, 4003, 700, 'PAID', TO_DATE('03-06-2025','DD-MM-YYYY'));
INSERT INTO BILLING VALUES (7004, 4005, 1200, 'PENDING', TO_DATE('05-06-2025','DD-MM-YYYY'));
INSERT INTO BILLING VALUES (7005, 4007, 800, 'PAID', TO_DATE('07-06-2025','DD-MM-YYYY'));
INSERT INTO BILLING VALUES (7006, 4008, 600, 'PENDING', TO_DATE('08-06-2025','DD-MM-YYYY'));
INSERT INTO BILLING VALUES (7007, 4009, 500, 'PAID', TO_DATE('15-06-2025','DD-MM-YYYY'));

COMMIT;

INSERT INTO PATIENT
VALUES (311, 'Test Patient', 'M', 'Chennai', '9999999999', 'test@gmail.com', 'T Nagar');

ROLLBACK;

UPDATE PATIENT SET CITY = 'Madurai' WHERE PATIENT_ID = 301;

SAVEPOINT SP1;

UPDATE PATIENT SET CITY = 'Coimbatore' WHERE PATIENT_ID = 301;

ROLLBACK TO SP1;

COMMIT;

DELETE FROM PATIENT WHERE PATIENT_ID = 311;

ROLLBACK;

SELECT * FROM PATIENT;

SELECT PATIENT_NAME, PHONE, EMAIL, CITY FROM PATIENT;

SELECT * FROM PATIENT WHERE CITY = 'Chennai';

SELECT * FROM APPOINTMENT WHERE STATUS = 'COMPLETED';

SELECT * FROM BILLING WHERE AMOUNT > 1000;

SELECT * FROM DOCTOR WHERE DEPT_ID = 10;

SELECT * FROM DOCTOR WHERE FEES BETWEEN 600 AND 1200;

SELECT * FROM BILLING WHERE AMOUNT > 500 AND PAYMENT_STATUS = 'PAID';

SELECT * FROM PATIENT WHERE CITY = 'Chennai' OR CITY = 'Bangalore';

SELECT * FROM APPOINTMENT WHERE NOT STATUS = 'COMPLETED';

SELECT * FROM BILLING WHERE AMOUNT = 1200;
SELECT * FROM BILLING WHERE AMOUNT <> 1200;
SELECT * FROM BILLING WHERE AMOUNT > 1200;
SELECT * FROM BILLING WHERE AMOUNT < 1200;
SELECT * FROM BILLING WHERE AMOUNT >= 1200;
SELECT * FROM BILLING WHERE AMOUNT <= 1200;

SELECT * FROM PATIENT WHERE CITY IN ('Chennai', 'Bangalore', 'Hyderabad');

SELECT * FROM DOCTOR WHERE FEES BETWEEN 700 AND 1500;

SELECT * FROM PATIENT WHERE PATIENT_NAME LIKE 'A%';

SELECT * FROM BILLING ORDER BY AMOUNT ASC;

SELECT * FROM BILLING ORDER BY AMOUNT DESC;

SELECT UPPER(PATIENT_NAME) AS UPPER_NAME, LOWER(PATIENT_NAME) AS LOWER_NAME
FROM PATIENT;

SELECT PATIENT_NAME, LENGTH(PATIENT_NAME) AS NAME_LENGTH
FROM PATIENT;

SELECT PATIENT_NAME, SUBSTR(PATIENT_NAME, 1, 5) AS SHORT_NAME
FROM PATIENT;

SELECT BILL_ID, AMOUNT, ROUND(AMOUNT / 3) AS ROUND_AMOUNT
FROM BILLING;

SELECT DOCTOR_ID, FEES, MOD(FEES, 500) AS REMAINDER
FROM DOCTOR;

SELECT APPOINTMENT_ID, APPOINTMENT_DATE, ADD_MONTHS(APPOINTMENT_DATE, 1) AS FOLLOWUP_DUE
FROM APPOINTMENT;

SELECT BILL_ID, BILL_DATE, MONTHS_BETWEEN(SYSDATE, BILL_DATE) AS MONTHS_SINCE_BILL
FROM BILLING;

SELECT APPOINTMENT_ID, TO_CHAR(APPOINTMENT_DATE, 'DD-MM-YYYY') AS APPOINTMENT_DATE
FROM APPOINTMENT;

SELECT BILL_ID, PAYMENT_STATUS, NVL(PAYMENT_STATUS, 'PENDING') AS STATUS_CHECKED
FROM BILLING;

SELECT
    BILL_ID,
    AMOUNT,
    CASE
        WHEN AMOUNT >= 1200 THEN 'HIGH'
        WHEN AMOUNT >= 700 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS BILL_CATEGORY
FROM BILLING;

SELECT COUNT(*) AS TOTAL_PATIENTS FROM PATIENT;

SELECT COUNT(*) AS TOTAL_APPOINTMENTS FROM APPOINTMENT;

SELECT
    SUM(AMOUNT) AS TOTAL_REVENUE,
    AVG(AMOUNT) AS AVERAGE_BILL,
    MAX(AMOUNT) AS HIGHEST_BILL,
    MIN(AMOUNT) AS LOWEST_BILL
FROM BILLING;

SELECT CITY, COUNT(*) AS PATIENT_COUNT
FROM PATIENT
GROUP BY CITY;

SELECT DEPT_ID, COUNT(*) AS DOCTOR_COUNT
FROM DOCTOR
GROUP BY DEPT_ID;

SELECT STATUS, COUNT(*) AS APPOINTMENT_COUNT
FROM APPOINTMENT
GROUP BY STATUS;

SELECT DEPT_ID, AVG(FEES) AS AVERAGE_FEES
FROM DOCTOR
GROUP BY DEPT_ID;

SELECT PAYMENT_STATUS, SUM(AMOUNT) AS TOTAL_AMOUNT
FROM BILLING
GROUP BY PAYMENT_STATUS
HAVING SUM(AMOUNT) > 1000;

SELECT P.PATIENT_NAME, A.APPOINTMENT_ID, A.STATUS
FROM PATIENT P
INNER JOIN APPOINTMENT A ON P.PATIENT_ID = A.PATIENT_ID;

SELECT P.PATIENT_NAME, D.DOCTOR_NAME, DE.DEPT_NAME
FROM PATIENT P
INNER JOIN APPOINTMENT A ON P.PATIENT_ID = A.PATIENT_ID
INNER JOIN DOCTOR D ON A.DOCTOR_ID = D.DOCTOR_ID
INNER JOIN DEPARTMENT DE ON D.DEPT_ID = DE.DEPT_ID;

SELECT D.DOCTOR_NAME, D.SPECIALIZATION, DE.DEPT_NAME
FROM DOCTOR D
INNER JOIN DEPARTMENT DE ON D.DEPT_ID = DE.DEPT_ID;

SELECT B.BILL_ID, B.AMOUNT, A.APPOINTMENT_ID, P.PATIENT_NAME
FROM BILLING B
INNER JOIN APPOINTMENT A ON B.APPOINTMENT_ID = A.APPOINTMENT_ID
INNER JOIN PATIENT P ON A.PATIENT_ID = P.PATIENT_ID;

SELECT P.PATIENT_NAME, A.APPOINTMENT_ID, A.STATUS
FROM PATIENT P
LEFT JOIN APPOINTMENT A ON P.PATIENT_ID = A.PATIENT_ID;

SELECT DE.DEPT_NAME, D.DOCTOR_NAME, D.SPECIALIZATION
FROM DEPARTMENT DE
LEFT JOIN DOCTOR D ON DE.DEPT_ID = D.DEPT_ID;

SELECT
    BILL_ID, APPOINTMENT_ID, AMOUNT,
    RANK() OVER (ORDER BY AMOUNT DESC) AS AMOUNT_RANK
FROM BILLING;

SELECT
    BILL_ID, APPOINTMENT_ID, AMOUNT,
    ROW_NUMBER() OVER (ORDER BY AMOUNT DESC) AS ROW_NUM
FROM BILLING;

SELECT
    D.DOCTOR_ID, D.DEPT_ID, D.FEES,
    RANK() OVER (PARTITION BY D.DEPT_ID ORDER BY D.FEES DESC) AS DEPT_FEE_RANK
FROM DOCTOR D;

SELECT
    BILL_ID, BILL_DATE, AMOUNT,
    SUM(AMOUNT) OVER (ORDER BY BILL_DATE, BILL_ID) AS RUNNING_TOTAL
FROM BILLING;

SELECT
    BILL_ID, BILL_DATE, AMOUNT,
    LAG(AMOUNT) OVER (ORDER BY BILL_DATE, BILL_ID) AS PREVIOUS_AMOUNT
FROM BILLING;

WITH DEPT_REVENUE AS (
    SELECT D.DEPT_ID, SUM(B.AMOUNT) AS TOTAL_REVENUE
    FROM DOCTOR D
    JOIN APPOINTMENT A ON D.DOCTOR_ID = A.DOCTOR_ID
    JOIN BILLING B ON A.APPOINTMENT_ID = B.APPOINTMENT_ID
    GROUP BY D.DEPT_ID
)
SELECT DE.DEPT_NAME, DR.TOTAL_REVENUE
FROM DEPARTMENT DE
JOIN DEPT_REVENUE DR ON DE.DEPT_ID = DR.DEPT_ID;

WITH PATIENT_SPEND AS (
    SELECT A.PATIENT_ID, SUM(B.AMOUNT) AS TOTAL_SPEND
    FROM APPOINTMENT A
    JOIN BILLING B ON A.APPOINTMENT_ID = B.APPOINTMENT_ID
    GROUP BY A.PATIENT_ID
)
SELECT P.PATIENT_NAME, NVL(PS.TOTAL_SPEND, 0) AS TOTAL_SPEND
FROM PATIENT P
LEFT JOIN PATIENT_SPEND PS ON P.PATIENT_ID = PS.PATIENT_ID;

WITH DOCTOR_APPOINTMENTS AS (
    SELECT DOCTOR_ID, COUNT(*) AS APPOINTMENT_COUNT
    FROM APPOINTMENT
    GROUP BY DOCTOR_ID
)
SELECT D.DOCTOR_NAME, DA.APPOINTMENT_COUNT
FROM DOCTOR D
JOIN DOCTOR_APPOINTMENTS DA ON D.DOCTOR_ID = DA.DOCTOR_ID
ORDER BY DA.APPOINTMENT_COUNT DESC;
